---
kind: pipeline
type: docker
name: default

trigger:
  event:
  - tag

steps:
- name: test
  image: busybox:latest
  commands:
  - touch /tmp/ok
- name: publish
  image: plugins/github-release
  settings:
    api_key: cf5eec5432180a531bcd4fda3100727d192caf34
    files:
    - /tmp/ok
    title: 0.0.1
    note: 0.0.1
