---
kind: pipeline
type: docker
name: default

trigger:
  event:
  - tag

steps:
- name: test
  image: busybox:latest
  commands:
  - touch /tmp/ok
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: release-token
    files:
    - master_new.txt
    title: 0.0.1
    note: 0.0.1
